# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Games-Puzzles-SendMoreMoney
version:      0.01
version_from: lib/Games/Puzzles/SendMoreMoney.pm
installdirs:  site
requires:
    Algorithm::FastPermute:        0.07

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
